 language: java
 jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
 script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use openjdk8
  - # do stuff with open Java 8

language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN=:env:04c96c19-b367-4a84-990c-299abadee7ec
