 language: java
 jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
 script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use openjdk8
  - # do stuff with open Java 8

language: java
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:      # 邮箱通知
  email: false

sudo: false #有定制化开发环境需要，默认false，不开启容器，编译效率高

before_install: 
  - pip install tensorflow #加sudo默认系统环境里的python，使用虚拟环境需加-E参数 
  - pip install codecov 
  - pip install coverage

install: true

script: 
  - coverage run Hello.java

after_success:
  - codecov #运行codecov
